// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("YC.PrettyPrinter")>]
[<assembly: AssemblyProductAttribute("YC.PrettyPrinter")>]
[<assembly: AssemblyDescriptionAttribute("Pretty printing library")>]
[<assembly: AssemblyVersionAttribute("0.0.5")>]
[<assembly: AssemblyFileVersionAttribute("0.0.5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "YC.PrettyPrinter"
    let [<Literal>] AssemblyProduct = "YC.PrettyPrinter"
    let [<Literal>] AssemblyDescription = "Pretty printing library"
    let [<Literal>] AssemblyVersion = "0.0.5"
    let [<Literal>] AssemblyFileVersion = "0.0.5"
